import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "luxe-navy": "#071626",
        "luxe-ink": "#0B1C2E",
        "luxe-ivory": "#FFFDF8",
        "luxe-gold": "#B9974F",
        "luxe-champagne": "#E2C171",
        "primary": "#000000",
        "primary-container": "#0d1c32",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#b9c7e4",
        "on-primary": "#ffffff",
        "on-primary-container": "#76849f",
        "on-primary-fixed": "#0d1c32",
        "on-primary-fixed-variant": "#39475f",
        "secondary": "#775a19",
        "secondary-container": "#fed488",
        "secondary-fixed": "#ffdea5",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#785a1a",
        "on-secondary-fixed": "#261900",
        "on-secondary-fixed-variant": "#5d4201",
        "tertiary": "#000000",
        "tertiary-container": "#002116",
        "tertiary-fixed": "#a6f2d1",
        "tertiary-fixed-dim": "#8bd6b6",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#479175",
        "on-tertiary-fixed": "#002116",
        "on-tertiary-fixed-variant": "#00513b",
        "background": "#fbf9fb",
        "surface": "#fbf9fb",
        "surface-bright": "#fbf9fb",
        "surface-dim": "#dbd9db",
        "surface-variant": "#e4e2e4",
        "surface-tint": "#515f78",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f5",
        "surface-container": "#efedef",
        "surface-container-high": "#eae7ea",
        "surface-container-highest": "#e4e2e4",
        "on-background": "#1b1b1d",
        "on-surface": "#1b1b1d",
        "on-surface-variant": "#44474d",
        "inverse-surface": "#303032",
        "inverse-on-surface": "#f2f0f2",
        "inverse-primary": "#b9c7e4",
        "outline": "#75777e",
        "outline-variant": "#c5c6cd",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        xs: "4px",
        base: "8px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "display-lg": ["Montserrat", "sans-serif"],
        "display-lg-mobile": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
      keyframes: {
        "pulse-ring": {
          "0%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(186,26,26,0.7)" },
          "70%": { transform: "scale(1)", boxShadow: "0 0 0 6px rgba(186,26,26,0)" },
          "100%": { transform: "scale(0.95)", boxShadow: "0 0 0 0 rgba(186,26,26,0)" },
        },
      },
      animation: {
        "pulse-live": "pulse-ring 2s cubic-bezier(0.215,0.61,0.355,1) infinite",
      },
      boxShadow: {
        "luxe-sm": "0 8px 30px rgba(18,31,44,.06)",
        "luxe-lg": "0 24px 70px rgba(7,22,38,.16)",
      },
    },
  },
  plugins: [],
};

export default config;
